!!python/object:argparse.Namespace
batch_size: 32
device: gpu
epochs: 100
input_size: 5
latent_size: 5
lr: 0.001
no_progress_bar: false
num_resamples: 10
steps_log_loss: 1000
steps_log_norm_params: 1000
